###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

dai-usaid-docker-webstarter-memcached:
  image: phpdockerio/memcached:latest
  container_name: dai-usaid-docker-webstarter-memcached

dai-usaid-docker-webstarter-redis:
  image: phpdockerio/redis:latest
  container_name: dai-usaid-docker-webstarter-redis

dai-usaid-docker-webstarter-mysql:
  image: mysql:5.7
  container_name: dai-usaid-docker-webstarter-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=web
    - MYSQL_USER=web
    - MYSQL_PASSWORD=web
    - MYSQL_HOST=IPADDRESS
  ports:
   - 3306:3306

dai-usaid-docker-webstarter-elasticsearch:
  image: elasticsearch:2.2
  container_name: dai-usaid-docker-webstarter-elasticsearch

dai-usaid-docker-webstarter-webserver:
  image: phpdockerio/nginx:latest
  container_name: dai-usaid-docker-webstarter-webserver
  volumes:
      - ..:/var/www/dai-usaid-docker-webstarter
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8080:80"
  links:
   - dai-usaid-docker-webstarter-php-fpm

dai-usaid-docker-webstarter-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: dai-usaid-docker-webstarter-php-fpm
  volumes:
    - ..:/var/www/dai-usaid-docker-webstarter
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini
  links:
    - dai-usaid-docker-webstarter-mysql
  environment:
    DB_HOST: dai-usaid-docker-webstarter-mysql
    DB_PORT: 3306
    DB_PASSWORD: root    
  links:
    - dai-usaid-docker-webstarter-memcached
    - dai-usaid-docker-webstarter-mysql
    - dai-usaid-docker-webstarter-redis
    - dai-usaid-docker-webstarter-elasticsearch
